---
- name: install xubuntu package
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - xubuntu-desktop
    - xfce4-clipman

- name: install lightdm package
  apt:
    name: lightdm
    state: present

- name: copy lightdm configuration file
  template:
    src: etc/lightdm/lightdm.conf.j2
    dest: /etc/lightdm/lightdm.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart lightdm
  when: xubuntu_autologin_user is defined

- name: enable lightdm service
  service:
    name: lightdm
    enabled: yes
    state: started
