---
dependencies:
  - role: angstwad.docker_ubuntu
    docker_opts: --storage-driver=devicemapper
  - role: jnv.unattended-upgrades
    unattended_package_blacklist: []
    unattended_automatic_reboot: false
    unattended_remove_unused_dependencies: true
  - role: tersmitten.fail2ban
    fail2ban_services:
      - name: ssh
        enabled: true
        port: ssh
        filter: sshd
        logpath: /var/log/auth.log
        maxretry: 6
  - role: franklinkim.ufw
    ufw_default_input_policy: DROP
    ufw_default_output_policy: ACCEPT
    ufw_default_forward_policy: ACCEPT
    ufw_state: enabled
    ufw_logging: 'off'
    ufw_reset: yes
    ufw_rules:
      - { rule: allow, port: 21 }
      - { rule: allow, port: 22 }
      - { rule: allow, from_ip: 192.168.1.0/24 }
      - { rule: allow, from_ip: 172.17.0.0/16 }
      - { rule: deny, from_ip: 191.98.163.0/25 }
      - { rule: deny, from_ip: 86.61.0.0/17 }
      - { rule: deny, from_ip: 91.224.160.0/23 }
      - { rule: deny, from_ip: 195.167.159.0/24 }
      - { rule: deny, from_ip: 91.224.160.0/23 }
      - { rule: deny, from_ip: 81.203.80.0/20 }
  - role: foundation
    foundation_users:
      - name: ps
        system: no
        shell: /bin/bash
        key: https://github.com/prakashsurya.keys
      - name: git
        system: yes
        shell: /usr/bin/git-shell
        key: https://github.com/prakashsurya.keys
    foundation_ssh_allow_users: 'ps git'
