---
dependencies:
  - role: angstwad.docker_ubuntu
    docker_opts: --storage-driver=devicemapper
  - role: dev-sec.ssh-hardening
    ssh_allow_users: ps
    ssh_print_motd: true
    ssh_print_last_log: true
  - role: jnv.unattended-upgrades
    unattended_package_blacklist: []
    unattended_automatic_reboot: true
    unattended_remove_unused_dependencies: true
  - role: tersmitten.fail2ban
    fail2ban_services:
      - name: ssh
        enabled: true
        port: ssh
        filter: sshd
        logpath: /var/log/auth.log
        maxretry: 6
  - role: franklinkim.ufw
    ufw_default_input_policy: ACCEPT
    ufw_default_output_policy: ACCEPT
    ufw_default_forward_policy: ACCEPT
    ufw_state: enabled
    ufw_logging: off
    ufw_reset: yes
    ufw_rules:
      - from_ip: 191.98.163.0/25
        rule: deny
