---
dependencies:
  - role: angstwad.docker_ubuntu
    docker_opts: --storage-driver=devicemapper
  - role: dev-sec.ssh-hardening
    ssh_allow_users: ps
    ssh_print_motd: true
    ssh_print_last_log: true
