---
- name: udevadm trigger
  command: udevadm trigger

- name: daemon reload
  command: systemctl daemon-reload

- name: restart x11vnc
  service:
    name: x11vnc
    state: restarted

- name: restart lightdm
  service:
    name: lightdm
    state: restarted

- name: restart networking
  service:
    name: networking
    state: restarted

- name: restart bind9
  service:
    name: bind9
    state: restarted

- name: restart vsftpd
  service:
    name: vsftpd
    state: restarted

- name: restart sshd
  service:
    name: sshd
    state: restarted
