---
- name: configure user groups
  group:
    name: "{{ item.name }}"
    system: "{{ item.system }}"
  with_items: "{{ foundation_users }}"
  when: foundation_users is defined

- name: configure users
  user:
    name: "{{ item.name }}"
    group: "{{ item.name }}"
    shell: "{{ item.shell }}"
    home: "/home/{{ item.name }}"
    system: "{{ item.system }}"
  with_items: "{{ foundation_users }}"
  when: foundation_users is defined

- name: configure home directory permissions
  file:
    path: "/home/{{ item.name }}"
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0755
  with_items: "{{ foundation_users }}"
  when: foundation_users is defined

- name: configure authorized_keys for users
  authorized_key:
    key: "{{ item.key | default('') }}"
    user: "{{ item.name }}"
  with_items: "{{ foundation_users }}"
  when: foundation_users is defined

- name: configure hostname
  hostname:
    name: "{{ foundation_hostname }}"
  when: foundation_hostname is defined
