---
- name: create user groups
  group:
    name: "{{ item.name }}"
    system: "{{ item.system }}"
  with_items: "{{ foundation_users }}"
  when: foundation_users is defined

- name: create users
  user:
    name: "{{ item.name }}"
    group: "{{ item.name }}"
    shell: "{{ item.shell }}"
    home: "/home/{{ item.name }}"
    system: "{{ item.system }}"
  with_items: "{{ foundation_users }}"
  when: foundation_users is defined

- name: set home directory permissions
  file:
    path: "/home/{{ item.name }}"
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0755
  with_items: "{{ foundation_users }}"
  when: foundation_users is defined
