---
dependencies:
  - role: jnv.unattended-upgrades
    unattended_package_blacklist: []
    unattended_automatic_reboot: false
    unattended_remove_unused_dependencies: true
  - role: foundation
    foundation_hostname: filbert
    foundation_ssh_allow_users: ps
    foundation_users:
      - name: ps
        system: no
        shell: /bin/bash
        key: https://github.com/prakashsurya.keys
  - role: google-chrome
  - role: hub
  - role: openfortivpn
  - role: taskwarrior
  - role: xubuntu
    xubuntu_autologin_user: ps
  - role: zoom
