- name: download and extract gopass command
  unarchive:
    src: https://www.justwatch.com/gopass/releases/1.0.0/gopass-1.0.0-linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: True
    owner: root
    group: root
    mode: 0755
    extra_opts:
      - '--strip-components=1'
