---
- name: install xubuntu package
  apt:
    name: xubuntu-desktop
    state: present

- name: install lightdm package
  apt:
    name: lightdm
    state: present

- name: copy lightdm configuration file
  copy:
    src: etc/lightdm/lightdm.conf
    dest: /etc/lightdm/lightdm.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart lightdm

- name: enable lightdm service
  service:
    name: lightdm
    enabled: yes
    state: started
