- name: install miscellaneous apt packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - cscope
    - docker.io
    - exuberant-ctags
    - nixnote2
    - openjdk-8-jdk
    - openjdk-8-jre
    - rdesktop
    - tmux
    - todotxt-cli
    - vim-nox

- name: install pip dependencies
  apt:
    name: python-pip
    state: present

- name: install miscellaneous pip packages
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - jrnl

#
# See also: https://github.com/pyenv/pyenv/wiki/common-build-problems
#
- name: install pyenv dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - make
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - wget
    - curl
    - llvm
    - libncurses5-dev
    - libncursesw5-dev
    - xz-utils
    - tk-dev

- name: install gopass dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - gnupg
    - git
    - rng-tools

- name: install gopass
  apt:
    deb:
      "https://github.com/justwatchcom/gopass/releases/download/\
       v1.7.0-alpha.1/gopass-1.7.0-alpha.1-linux-amd64.deb"

- name: add drive apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 7086E9CC7EC3233B

- name: add drive apt repository
  apt_repository:
    repo: "deb http://shaggytwodope.github.io/repo ./"
    state: present
    filename: google-drive-cli

- name: install drive packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - dirmngr
    - drive
