- name: install miscellaneous packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - docker.io
    - nixnote2
    - openjdk-8-jdk
    - openjdk-8-jre
    - rdesktop
    - tmux
    - todotxt-cli
    - vim

#
# See also: https://github.com/pyenv/pyenv/wiki/common-build-problems
#
- name: install pyenv dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - make
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - wget
    - curl
    - llvm
    - libncurses5-dev
    - libncursesw5-dev
    - xz-utils
    - tk-dev

- name: install gopass dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - gnupg
    - git
    - rng-tools

- name: install gopass
  apt:
    deb:
      "https://github.com/justwatchcom/gopass/releases/download/\
       v1.7.0-alpha.1/gopass-1.7.0-alpha.1-linux-amd64.deb"
