---
- hosts: localhost
  vars:
    foundation_hostname: hefer
    foundation_ssh_allow_users: ps
    foundation_users:
      - name: ps
        system: no
        shell: /bin/bash
        key: https://github.com/prakashsurya.keys
    xubuntu_autologin_user: ps
  roles:
    - foundation
    - google-chrome
    - steam
    - xubuntu
