---
- hosts: localhost
  vars:
    foundation_users:
      - name: ps
        system: no
        shell: /bin/bash
    foundation_ssh_allow_users: ps
    xubuntu_autologin_user: ps
  roles:
    - foundation
    - xubuntu
