---
- name: install taskwarrior apt packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - taskwarrior
    - timewarrior

- name: install taskopen dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - libjson-perl

- name: create taskopen /opt directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt
    - /opt/taskopen
    - /opt/taskopen/src

- name: checkout taskopen source code
  git:
    repo: https://github.com/ValiValpas/taskopen.git
    dest: /opt/taskopen/src
    version: v1.1.3
    update: no
  register: checkout

- name: perform taskopen build and installation
  shell: "{{ item }}"
  args:
    chdir: /opt/taskopen/src
  with_items:
    - make SHELL=/bin/bash PREFIX=/opt/taskopen
    - make SHELL=/bin/bash PREFIX=/opt/taskopen install
  when: checkout.changed

- name: create bugwarrior /opt directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt
    - /opt/bugwarrior
    - /opt/bugwarrior/src

- name: checkout bugwarrior source code
  git:
    repo: https://github.com/ralphbean/bugwarrior.git
    dest: /opt/bugwarrior/src
    version: develop
    update: no
  register: checkout

- name: perform bugwarrior build and installation
  shell: "{{ item }}"
  args:
    chdir: /opt/bugwarrior/src
  with_items:
    - python setup.py install
  when: checkout.changed

- name: install pip
  apt:
    name: python-pip
    state: present

- name: install bugwarrior pip packages
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - bugwarrior[gmail]
    - bugwarrior[keyring]
